# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the length of the chain
#' @param thin the number of Binomial(thin, y)
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(1000,50)
#' plot(rnC[1,],type='l')
#' plot(rnC[2,],type='l')
#' }
#' @export
gibbsC <- function(N, thin) {
    .Call('_StatComp21049_gibbsC', PACKAGE = 'StatComp21049', N, thin)
}

